### PR TITLE
Refactor login method and extract email link input to utils.py

### PR DESCRIPTION
**Pull request by wingeva1986**

### CODE REVIEW

**Comment by nathanrchn** [comment]
Hello, what is the purpose of this pull request because it only creates an empty function?

**Comment by wingeva1986** [comment]
> Hello, what is the purpose of this pull request because it only creates an empty function?

maybe easy to rewrite your own method to check new mail and get the link：）

**Comment by wingeva1986** [comment]
> > Hello, what is the purpose of this pull request because it only creates an empty function?
> 
> maybe easy to rewrite your own method to automatically check new mail and get the link ：）

**Comment by wingeva1986** [comment]
> Hello, what is the purpose of this pull request because it only creates an empty function?

oh,sorry,it's not Python style.

**Pull request closed without merging**
